idf_component_register(
    SRCS "jonisk.cpp"
    "blink.cpp"
    "NVSStorage.cpp"
    "jfixture.cpp"
    "OTAUpdater.cpp"
    "I2CWrapper.cpp"
    "BQ25792.cpp"
    "generated/simple.pb.c"
    "JProtoExample.cpp"
    "UART.cpp"
    "dimmer.cpp"
    "lagger.cpp"
    "parser.cpp"
    "espnow_handler.cpp"
    "ethernet_handler.cpp"
    "JOsc.cpp"
    "JWavetable.cpp"
    "JEnv.cpp"
    "Event.cpp"
    "JEvent_Perlin.cpp"
    "JRect.cpp"
    "expRandLines.cpp"
    "jfixture_graphics.cpp"
    "jfixture_addr.cpp"
    "motor_controller.cpp"
    INCLUDE_DIRS . generated
    REQUIRES esp_driver_gpio mbedtls nvs_flash esp_http_client esp_https_ota esp_wifi esp_event esp_netif freertos esp_driver_i2c esp_driver_ledc esp_driver_uart esp_timer nanopb led_strip esp_eth esp_driver_spi
)
